### ISSUE TITLE
Error starting chat on Galaxy A6+ Android 10, Galaxy S6 Edge Android 7, Nexus 6P Android 8.1

### ISSUE THREAD

**Issue by rezafaraji93** [crisp-im/crisp-sdk-android#104] opened 2022-04-18 05:37 UTC
I get E/CrispSocket: (Initialization Error) Error starting chat on Android 10 (Galaxy A6+) and not on Android 7, 8, 11 or 12

**Comment by Doc1faux** [comment] 2022-04-19 18:32
Hi @rezafaraji93 and thank you for your feedback.

I've just tested on Android 10 and I have no issue :/
Maybe it is an issue with this specific device? Did you tried on another Android 10 device or emulator?
I don't have a Samsung device with me to try to reproduce it :/

**Comment by Doc1faux** [comment] 2022-08-06 16:28
_Moved from @oanaperes post in #127_

> When trying to open chat we get "Error starting chat" and we can try again as many times as we like but it never opens. This happens on Samsung Galaxy S6 Edge with Android 7.0, Nexus 6P with Android 8.1.0.
>Environment: "react-native-crisp-chat-sdk": "0.10.2", 'im.crisp:crisp-sdk:1.0.9', targetSdkVersion = 31, "react-native": "0.66.4".
> 
> Logs From Android Studio when "Error Starting chat" is received:
>"2022-07-28 10:07:[11.687 29765-29857](callto:11.687 29765-29857)/com.client I/CrispSocket: Chat initialization timeout has been exceeded.
>2022-07-28 10:07:[11.688 29765-29857](callto:11.688 29765-29857)/com.client D/CrispSocket: Disconnecting...
>2022-07-28 10:07:[11.688 29765-29857](callto:11.688 29765-29857)/com.client D/CrispSocket: Clearing chat initialization timeout.
>2022-07-28 10:07:[11.692 29765-29857](callto:11.692 29765-29857)/com.client E/CrispSocket: (Initialization Error) Error starting chat
>2022-07-28 10:07:[11.701 29765-30210](callto:11.701 29765-30210)/com.client E/CrispSocket: A websocket error occured. 
>Name: connect_timeout 
>Args: [ 15000 ]"

**Comment by Doc1faux** [comment] 2022-08-24 16:08
Hi @rezafaraji93 & @oanaperes,

`1.0.13` has just been released and it could fix the issue you are facing.
Could you give it a try?

If you want more details about it, I have opened issue #133 especially to explain what has been fixed.

**Comment by Doc1faux** [comment] 2024-02-05 13:01
Without any feedback since more than a year, I consider this issue fixed.
Closing it.

**Closed by Doc1faux** 2024-02-05 13:01 UTC
Labels: bug, native-sdk, discussion
