### ISSUE TITLE
Any way to get unread message counts & push notifications in-app?

### ISSUE THREAD

**Issue by SeanBlahovici** [crisp-im/crisp-sdk-android#189] opened 2024-09-10 13:45 UTC
Hello,

I am combing through the documentation, and it looks like the SDK does not offer a method to retrieve unread counts of active chats, or push notifications to alert the user of a new message.

Are there any plans of supporting these features, or did I just not find them?

I am using version 2.0.2beta3, thanks!

Edit: I see I can probably achieve this with webhooks. It would be much easier if the SDK provided something though! At least like a messageReceived callback or something, so I can add an unread count on my support widget!

**Comment by Doc1faux** [comment] 2024-09-12 09:21
Hi @SeanBlahovici and thank you for your feedback,
This is a duplicate of #172, I let you refer to it and I close yours ;)

**Closed by Doc1faux** 2024-09-12 09:21 UTC
Labels: duplicate, native-sdk, feature
