### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by pdprober** [crisp-im/crisp-sdk-android#129] opened 2022-08-09 03:44 UTC
**OS Version** 
       Android 12
**Phones**  
      vivo 1907
**SDK Version** 
      1.0.12
**Crash logs**
   Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String im.crisp.client.internal.i.a.f()' on a 
   null object reference
       at im.crisp.client.internal.t.b.$r8$lambda$33VlFY_VHO3HHcdwHj-EFdlijBg(b.java:10)
       at im.crisp.client.internal.j.a.a(a.java:22)
       at im.crisp.client.internal.j.a.onPostExecute(a.java:2)
       at android.os.AsyncTask.finish(AsyncTask.java:771)
       at android.os.AsyncTask.access$900(AsyncTask.java:199)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8396)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by Doc1faux** [comment] 2022-08-09 08:35
Hi @pdprober and thank you for your feedback.

This is a duplicate of #126 which is already fixed and is waiting for a new release, so I close this one.

**Closed by Doc1faux** 2022-08-09 08:35 UTC
Labels: duplicate, native-sdk, crash
