### ISSUE TITLE
Attempt to invoke virtual method 'boolean r2.a.F(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by kakarrot** [crisp-im/crisp-sdk-android#108] opened 2022-05-05 03:58 UTC
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean r2.a.F(java.lang.String)' on a null object reference
       at im.crisp.client.internal.a.b.$r8$lambda$DFkpIYdEe1-6xt8rTZnD7wZZf7U(b.java:2)
       at im.crisp.client.internal.a.b.c(b.java:2)
       at im.crisp.client.Crisp.resetChatSession(Crisp.java:21)
       at im.crisp.client.Crisp.configure(Crisp.java:63)
       at com.ya.core.base.BaseApp.onCreate(BaseApp.java:28)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202)
       at android.app.ActivityThread.access$2200(ActivityThread.java:296)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by Doc1faux** [comment] 2022-05-05 07:19
Hi @kakarrot and thank you for your feedback.

Could you please specify the SDK version? I suppose it is the latest `1.0.11`?
Could your provide me also the Android version on which the app was running, maybe the specific device and also what is the context of the crash?

THanks in advance :)

**Comment by Doc1faux** [comment] 2022-05-05 07:56
This is strange because in the latest `1.0.11`, there is no obfuscated `im.crisp.client.internal.a.b` package nor class :/
As I can deduce from the stacktrace, you were trying to configure a different websiteID than the one you already configured? I am not able to reproduce the crash in this case :/
Maybe you could provide more details :)

**Comment by kakarrot** [comment] 2022-05-05 10:23
I used SDK is 1.0.9，because I used exoplayer and SDK's exoplayer had upgrade to latest version from 1.0.10，I need time to modify my code to adapt it.
Device:  HUAWEI P smart 2019
Android Version: 10

**Comment by Doc1faux** [comment] 2022-05-19 11:51
OK, so this is happenning on `Crisp.resetChatSession(Context)` while trying to clear cached website icon.
On some edgy cases, I suppose cache could be `null` in some way implying a crash.
Fixed it and will be released in `1.0.12`.

**Closed** 2022-06-09 13:44 UTC
Labels: native-sdk, crash, discussion, shipped in next release
