### ISSUE TITLE
Display messages sent `from` `user` from REST API

### ISSUE THREAD

**Issue by baronha** [crisp-im/crisp-sdk-android#166] opened 2024-01-31 03:34 UTC
I use REST API to send messages from `user` to `operator` via API: https://docs.crisp.chat/references/rest-api/v1/#send-a-message-in-conversation
on iOS works perfectly. But Android Socket does not listen to chat messages.
 
Results of the conversation:

CRM: 
![screenshot-2024-01-30-at-11525_p2ucmz](https://github.com/crisp-im/crisp-sdk-android/assets/23580920/a01b647a-388c-478f-8b1d-1aca88786a42)

---

Android SDK:
![screenshot-2024-01-30-at-11522_p9vq58](https://github.com/crisp-im/crisp-sdk-android/assets/23580920/6b2b9e87-4782-49d2-9380-fb3f9d16f1e5)

**Comment by Doc1faux** [comment] 2024-01-31 14:44
Hi @baronha,

The issue is not related to socket but the `carousel` message type which is not currently supported by the Android SDK so it is ignored.
The upcoming release which should be available in February will support it.
I have opened issue #167 to keep track of it.

I close the issue

**Comment by baronha** [comment] 2024-02-01 03:30
Not the carousel type but also the `text` is not displayed correctly.
![screenshot-2024-01-30-at-18082_kbj160](https://github.com/crisp-im/crisp-sdk-android/assets/23580920/a4afe61e-9ab6-46de-9266-b00888ac0ceb)

![Screenshot 2024-02-01 at 10 28 58](https://github.com/crisp-im/crisp-sdk-android/assets/23580920/562e4107-bf07-4ffa-8cf0-7a6525c3e52a)

**Comment by Doc1faux** [comment] 2024-02-01 08:57
As it seems not tied to `carousel` message type, I reopened the issue.

I have investigated this morning and I had no issue until I read twice your first comment and saw you were talking about sending messages *from user to operator*, and indeed, this case is not currently handled as I was dropping any sent message I did not have in cache...

I already fixed it a month ago for the next upcoming release this month :)
I keep you up-to-date when it will be available.

**Comment by Doc1faux** [comment] 2024-02-21 18:35
This should be fixed in [`2.0.0beta1`](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v2.0.0beta1).
This build is for preview as it still lacks some minor features and needs some optimizations :)

**Closed by Doc1faux** 2024-02-21 18:35 UTC
Labels: bug, native-sdk, planned
