### ISSUE TITLE
Chat not scrolled to the last message

### ISSUE THREAD

**Issue by francescogatto** [crisp-im/crisp-sdk-android#83] opened 2021-12-07 20:45 UTC
When the chat activity starts, the chat history doesn't go to the last message

**Comment by Doc1faux** [comment] 2022-02-11 16:07
Hello @francescogatto and thank you for your feedback.
I was not able to reproduce it until I reproduced #67, #75 & #81.
As I fixed them in the recently released 1.0.9, it should be fixed right now.
I let you reopen the issue if you meet it again.

**Closed by Doc1faux** 2022-02-11 16:07 UTC
