### ISSUE TITLE
[Bug] java.lang.IllegalStateException: no_session

### ISSUE THREAD

**Issue by briskemen** [crisp-im/crisp-sdk-android#54] opened 2021-05-14 03:10 UTC
at im.crisp.client.b.b.b.<init>(Unknown Source:102)
        at im.crisp.client.b.b.b.a(Unknown Source:9)
        at im.crisp.client.b.b.b.b(Unknown Source:1)
        at im.crisp.client.b.e.b.b.h(Unknown Source:15)
        at im.crisp.client.b.e.b.b.a(Unknown Source:3)
        at im.crisp.client.b.e.b.b.lambda$ruuIttC9-hyYHOklD9IrCtkkfGA(Unknown Source:0)
        at im.crisp.client.b.e.b.-$$Lambda$b$ruuIttC9-hyYHOklD9IrCtkkfGA.onEditorAction(Unknown Source:2)
        at android.widget.TextView.onEditorAction(TextView.java:7082)
        at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:371)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:94)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

action:
- start ChatActivity
- input some msg, and click send btn
- and that crash

sdk_version = 1.0.4

**Comment by eliottvincent** [comment] 2021-07-07 09:36
Hello! Can you please try with the new version we released (1.0.7)?

**Comment by Doc1faux** [comment] 2022-02-11 15:04
As said in #52, it should have been addressed in 1.0.5
Duplicate of https://github.com/crisp-im/crisp-sdk-android/issues/52#issuecomment-838436754

**Closed by Doc1faux** 2022-02-11 15:04 UTC
