### ISSUE TITLE
Chat bot button list cutted

### ISSUE THREAD

**Issue by francescogatto** [crisp-im/crisp-sdk-android#84] opened 2021-12-08 13:02 UTC
![Screenshot_20211208-132010_Reddito di Cittadinanza App.jpg](https://user-images.githubusercontent.com/4219260/145212743-9b9372a0-d9bf-44c3-a736-a777a0ed43af.jpg)

The UI shows only 5 of 6 buttons

**Comment by baptistejamin** [comment] 2021-12-31 09:01
Can you show the same screenshot with the Crisp Web SDK?

**Comment by francescogatto** [comment] 2022-01-04 11:18
![Screenshot_20220104-120552](https://user-images.githubusercontent.com/4219260/148051437-f514cb96-53af-4240-8b04-171aa3344498.jpg)
![Screenshot_20220104-120450](https://user-images.githubusercontent.com/4219260/148051443-65c2096a-8f25-4e1a-8b64-e0424d7a7a01.jpg)

**Comment by Doc1faux** [comment] 2022-02-11 16:31
Duplicate of #63

**Closed by Doc1faux** 2022-02-11 16:31 UTC

**Comment by Doc1faux** [comment] 2022-02-11 18:08
Hello @francescogatto and thank your for your feedback :)
This is a duplicate of #63 so I closed it.
I let you follow the conversation on [this issue](https://github.com/crisp-im/crisp-sdk-android/issues/63) instead :)
