### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.leocare.app/im.crisp.client.ChatActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment im.crisp.client.internal.ui.a.a.c: could not find Fragment constructor

### ISSUE THREAD

**Issue by StevenWatremez** [crisp-im/crisp-sdk-android#115] opened 2022-05-19 15:07 UTC
# Context 
Same as the previous one we have an other crash that occurs 2 times for 2 users. 

# Crash log
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.leocare.app/im.crisp.client.ChatActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment im.crisp.client.internal.ui.a.a.c: could not find Fragment constructor
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4037)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4203)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6340)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6205)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:65)
       at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6294)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)


Caused by androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment im.crisp.client.internal.ui.a.a.c: could not find Fragment constructor
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:630)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:448)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
       at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2410)
       at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2584)
       at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:116)
       at androidx.fragment.app.FragmentActivity.lambda$init$1$androidx-fragment-app-FragmentActivity(FragmentActivity.java:128)
       at androidx.fragment.app.FragmentActivity$$ExternalSyntheticLambda0.onContextAvailable(:2)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:320)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:249)
       at im.crisp.client.ChatActivity.onCreate()
       at android.app.Activity.performCreate(Activity.java:8282)
       at android.app.Activity.performCreate(Activity.java:8262)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4011)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4203)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6340)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6205)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:65)
       at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6294)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)


Caused by java.lang.NoSuchMethodException: im.crisp.client.internal.ui.a.a.c.<init> []
       at java.lang.Class.getConstructor0(Class.java:2363)
       at java.lang.Class.getConstructor(Class.java:1759)
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:615)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:448)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
       at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2410)
       at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2584)
       at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:116)
       at androidx.fragment.app.FragmentActivity.lambda$init$1$androidx-fragment-app-FragmentActivity(FragmentActivity.java:128)
       at androidx.fragment.app.FragmentActivity$$ExternalSyntheticLambda0.onContextAvailable(:2)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:320)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:249)
       at im.crisp.client.ChatActivity.onCreate()
       at android.app.Activity.performCreate(Activity.java:8282)
       at android.app.Activity.performCreate(Activity.java:8262)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4011)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4203)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6340)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6205)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:65)
       at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6294)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

# Information
```
OS Version : Android 12 et 11
Phones : Galaxy S20 FE, Redmi Note 11
SDK Version : 1.0.9
```

**Comment by Doc1faux** [comment] 2022-05-19 19:18
Hello @StevenWatremez and thank your for your feedback.

This is a duplicate of #109 so I'm closing it. You could track its resolution on this issue.
However, I add your stacktrace to it as it is more detailed

**Closed by Doc1faux** 2022-05-19 19:18 UTC
Labels: duplicate, native-sdk, crash
