### ISSUE TITLE
Start ChatActivity crash

### ISSUE THREAD

**Issue by DavidCap** [crisp-im/crisp-sdk-android#165] opened 2024-01-03 12:53 UTC
OS Version :Android 13
Phones : SM-S918U Galaxy S23 Ultra
SDK Version : 1.0.13
Crash logs:

Exception:
ExceptionData{className='java.util.Formatter$FormatSpecifierParser', type='java.util.UnknownFormatConversionException', methodName='peek', lineNumber=2795}

Cause:
Conversion = 'End of String'

StackTrace:
java.util.UnknownFormatConversionException: Conversion = 'End of String'
 at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2795)
 at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2764)
 at java.util.Formatter.parse(Formatter.java:2711)
 at java.util.Formatter.format(Formatter.java:2660)
 at java.util.Formatter.format(Formatter.java:2614)
 at java.lang.String.format(String.java:4058)
 at android.content.res.Resources.getString(Resources.java:630)
 at im.crisp.client.internal.t.e.a(Unknown Source:54)
 at im.crisp.client.internal.t.e.a(Unknown Source:260)
 at im.crisp.client.internal.t.e.onCreateView(Unknown Source:113)
 at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
 at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
 at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
 at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
 at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
 at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
 at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
 at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
 at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
 at im.crisp.client.ChatActivity.onStart(Unknown Source:0)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
 at android.app.Activity.performStart(Activity.java:8616)
 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4194)
 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8747)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
 
Please check the code and let me know how to fix it.

**Comment by Doc1faux** [comment] 2024-01-05 08:25
Hi @DavidCap and thank you for your feedback,

This crash seems to be a duplicate of #150 which was fixed in [1.0.15](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v1.0.15).
Indeed, strings of the Android SDK are parsed from the ones of the Web SDK but some from various locales were not well formatted.
After diving into your stacktrace, it seems the crash is caused by one of them.
So you can update the SDK to 1.0.15 to fix the issue :)

**Closed by Doc1faux** 2024-01-05 08:25 UTC
Labels: duplicate, native-sdk, crash
