### ISSUE TITLE
[Crash Report] NullPointerException in LayerDrawable.isProjected( )  - Potential View Rendering Issue

### ISSUE THREAD

**Issue by surendra-singh-ids** [crisp-im/crisp-sdk-android#186] opened 2024-08-30 05:20 UTC
I'm encountering few crashes in the app that are being reported in Firebase Crashlytics, specifically a NullPointerException within android.graphics.drawable.LayerDrawable.isProjected(). This seems to be happening during the view layout process, potentially indicating an issue with how drawables are being handled or rendered.

**Crash #1**
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.isProjected()' on a null object reference
       at android.graphics.drawable.LayerDrawable.isProjected(LayerDrawable.java:417)
       at android.view.View.invalidateInternal(View.java:18038)
       at android.view.View.invalidate(View.java:17987)
       at android.view.View.setFrame(View.java:22573)
       at android.view.View.layout(View.java:22423)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:576)
       at im.crisp.client.internal.utils.BottomSheetNestedScrollBehavior.onLayoutChild()
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1041)
       at android.view.View.layout(View.java:22426)
       at android.view.ViewGroup.layout(ViewGroup.java:6584)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3363)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2827)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8496)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
       at android.view.Choreographer.doCallbacks(Choreographer.java:764)
       at android.view.Choreographer.doFrame(Choreographer.java:699)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
       
 **Crash #2**
 Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getSmoothCornerState()' on a null object reference
       at android.graphics.drawable.LayerDrawable.getSmoothCornerState(LayerDrawable.java:1032)
       at android.view.View.getDrawableRenderNode(View.java:25122)
       at android.view.View.drawBackground(View.java:25049)
       at android.view.View.draw(View.java:24777)
       at android.view.View.updateDisplayListIfDirty(View.java:23584)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.updateDisplayListIfDirty(View.java:23571)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.updateDisplayListIfDirty(View.java:23571)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.updateDisplayListIfDirty(View.java:23571)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.updateDisplayListIfDirty(View.java:23571)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.draw(View.java:24801)
       at android.view.View.updateDisplayListIfDirty(View.java:23584)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.updateDisplayListIfDirty(View.java:23571)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.updateDisplayListIfDirty(View.java:23571)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.updateDisplayListIfDirty(View.java:23571)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.updateDisplayListIfDirty(View.java:23571)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.updateDisplayListIfDirty(View.java:23571)
       at android.view.View.draw(View.java:24488)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
       at android.view.View.draw(View.java:24801)
       at com.android.internal.policy.DecorView.draw(DecorView.java:896)
       at android.view.View.updateDisplayListIfDirty(View.java:23584)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:736)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:745)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:851)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5720)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5363)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4457)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3014)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10526)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1671)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1680)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1191)
       at android.view.Choreographer.doFrame(Choreographer.java:1063)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1650)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:222)
       at android.os.Looper.loop(Looper.java:314)
       at android.app.ActivityThread.main(ActivityThread.java:8670)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

I haven't been able to reproduce this crash locally, so the exact steps to trigger it are unknown.

**Comment by Doc1faux** [comment] 2024-08-30 07:19
Duplicate of #179, closing

**Closed by Doc1faux** 2024-08-30 07:19 UTC
